//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaksinApp.KonfirmVaksinService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data_Pasien", Namespace="http://schemas.datacontract.org/2004/07/KonfirmVaksinService")]
    [System.SerializableAttribute()]
    public partial class Data_Pasien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_pasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_vaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nik_pasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string no_rekam_medisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_pasien {
            get {
                return this.id_pasienField;
            }
            set {
                if ((this.id_pasienField.Equals(value) != true)) {
                    this.id_pasienField = value;
                    this.RaisePropertyChanged("id_pasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_vaksin {
            get {
                return this.id_vaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.id_vaksinField, value) != true)) {
                    this.id_vaksinField = value;
                    this.RaisePropertyChanged("id_vaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nik_pasien {
            get {
                return this.nik_pasienField;
            }
            set {
                if ((object.ReferenceEquals(this.nik_pasienField, value) != true)) {
                    this.nik_pasienField = value;
                    this.RaisePropertyChanged("nik_pasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string no_rekam_medis {
            get {
                return this.no_rekam_medisField;
            }
            set {
                if ((object.ReferenceEquals(this.no_rekam_medisField, value) != true)) {
                    this.no_rekam_medisField = value;
                    this.RaisePropertyChanged("no_rekam_medis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KonfirmVaksinService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertLaporan", ReplyAction="http://tempuri.org/IService1/InsertLaporanResponse")]
        void InsertLaporan(VaksinApp.KonfirmVaksinService.Data_Pasien obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertLaporan", ReplyAction="http://tempuri.org/IService1/InsertLaporanResponse")]
        System.Threading.Tasks.Task InsertLaporanAsync(VaksinApp.KonfirmVaksinService.Data_Pasien obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPasien", ReplyAction="http://tempuri.org/IService1/GetPasienResponse")]
        VaksinApp.KonfirmVaksinService.Data_Pasien[] GetPasien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPasien", ReplyAction="http://tempuri.org/IService1/GetPasienResponse")]
        System.Threading.Tasks.Task<VaksinApp.KonfirmVaksinService.Data_Pasien[]> GetPasienAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : VaksinApp.KonfirmVaksinService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<VaksinApp.KonfirmVaksinService.IService1>, VaksinApp.KonfirmVaksinService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertLaporan(VaksinApp.KonfirmVaksinService.Data_Pasien obj) {
            base.Channel.InsertLaporan(obj);
        }
        
        public System.Threading.Tasks.Task InsertLaporanAsync(VaksinApp.KonfirmVaksinService.Data_Pasien obj) {
            return base.Channel.InsertLaporanAsync(obj);
        }
        
        public VaksinApp.KonfirmVaksinService.Data_Pasien[] GetPasien() {
            return base.Channel.GetPasien();
        }
        
        public System.Threading.Tasks.Task<VaksinApp.KonfirmVaksinService.Data_Pasien[]> GetPasienAsync() {
            return base.Channel.GetPasienAsync();
        }
    }
}
