//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrasiVaksin_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaksinData
    {
        public string no_register { get; set; }
        public Nullable<System.DateTime> tanggal_dibuat { get; set; }
    }
}
