//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonfirmasiVaksin_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Pasien
    {
        public int id_pasien { get; set; }
        public string no_rekam_medis { get; set; }
        public string id_vaksin { get; set; }
        public string nik_pasien { get; set; }
    }
}
