//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaksinApp.VaksinRegistService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VaksinData", Namespace="http://schemas.datacontract.org/2004/07/RegistrasiVaksin_Service")]
    [System.SerializableAttribute()]
    public partial class VaksinData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string no_registerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> tanggal_dibuatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string no_register {
            get {
                return this.no_registerField;
            }
            set {
                if ((object.ReferenceEquals(this.no_registerField, value) != true)) {
                    this.no_registerField = value;
                    this.RaisePropertyChanged("no_register");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> tanggal_dibuat {
            get {
                return this.tanggal_dibuatField;
            }
            set {
                if ((this.tanggal_dibuatField.Equals(value) != true)) {
                    this.tanggal_dibuatField = value;
                    this.RaisePropertyChanged("tanggal_dibuat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VaksinRegistService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVaksin", ReplyAction="http://tempuri.org/IService1/GetVaksinResponse")]
        VaksinApp.VaksinRegistService.VaksinData[] GetVaksin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVaksin", ReplyAction="http://tempuri.org/IService1/GetVaksinResponse")]
        System.Threading.Tasks.Task<VaksinApp.VaksinRegistService.VaksinData[]> GetVaksinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertVaksin", ReplyAction="http://tempuri.org/IService1/InsertVaksinResponse")]
        void InsertVaksin(VaksinApp.VaksinRegistService.VaksinData obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertVaksin", ReplyAction="http://tempuri.org/IService1/InsertVaksinResponse")]
        System.Threading.Tasks.Task InsertVaksinAsync(VaksinApp.VaksinRegistService.VaksinData obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateVaksin", ReplyAction="http://tempuri.org/IService1/UpdateVaksinResponse")]
        void UpdateVaksin(VaksinApp.VaksinRegistService.VaksinData obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateVaksin", ReplyAction="http://tempuri.org/IService1/UpdateVaksinResponse")]
        System.Threading.Tasks.Task UpdateVaksinAsync(VaksinApp.VaksinRegistService.VaksinData obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteVaksin", ReplyAction="http://tempuri.org/IService1/DeleteVaksinResponse")]
        void DeleteVaksin(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteVaksin", ReplyAction="http://tempuri.org/IService1/DeleteVaksinResponse")]
        System.Threading.Tasks.Task DeleteVaksinAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataById", ReplyAction="http://tempuri.org/IService1/GetDataByIdResponse")]
        VaksinApp.VaksinRegistService.VaksinData GetDataById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataById", ReplyAction="http://tempuri.org/IService1/GetDataByIdResponse")]
        System.Threading.Tasks.Task<VaksinApp.VaksinRegistService.VaksinData> GetDataByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        void GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : VaksinApp.VaksinRegistService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<VaksinApp.VaksinRegistService.IService1>, VaksinApp.VaksinRegistService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VaksinApp.VaksinRegistService.VaksinData[] GetVaksin() {
            return base.Channel.GetVaksin();
        }
        
        public System.Threading.Tasks.Task<VaksinApp.VaksinRegistService.VaksinData[]> GetVaksinAsync() {
            return base.Channel.GetVaksinAsync();
        }
        
        public void InsertVaksin(VaksinApp.VaksinRegistService.VaksinData obj) {
            base.Channel.InsertVaksin(obj);
        }
        
        public System.Threading.Tasks.Task InsertVaksinAsync(VaksinApp.VaksinRegistService.VaksinData obj) {
            return base.Channel.InsertVaksinAsync(obj);
        }
        
        public void UpdateVaksin(VaksinApp.VaksinRegistService.VaksinData obj) {
            base.Channel.UpdateVaksin(obj);
        }
        
        public System.Threading.Tasks.Task UpdateVaksinAsync(VaksinApp.VaksinRegistService.VaksinData obj) {
            return base.Channel.UpdateVaksinAsync(obj);
        }
        
        public void DeleteVaksin(string id) {
            base.Channel.DeleteVaksin(id);
        }
        
        public System.Threading.Tasks.Task DeleteVaksinAsync(string id) {
            return base.Channel.DeleteVaksinAsync(id);
        }
        
        public VaksinApp.VaksinRegistService.VaksinData GetDataById(string id) {
            return base.Channel.GetDataById(id);
        }
        
        public System.Threading.Tasks.Task<VaksinApp.VaksinRegistService.VaksinData> GetDataByIdAsync(string id) {
            return base.Channel.GetDataByIdAsync(id);
        }
        
        public void GetData() {
            base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
